Setup display for Voter Registration Status
MI-Vote/mivote-android pull request #9
Opened 2020-10-10 15:54 UTC by scottschmitz

Display the appropriate registration status for the User. This is assuming that the previous MR would make the request, if not I can add it into this one. 

If anyone has any suggestions for how to get the background color to actually change that would be awesome. As it stands all of the colors except for the background color change as you would expect.

![image](https://user-images.githubusercontent.com/1085240/95659453-29d1aa00-0aef-11eb-9bef-27f7b299773d.png)

Closes #8

2020-10-11 04:01 UTC, joshfriend requested changes

2020-10-11 04:01 UTC, joshfriend commented on app/src/main/java/com/fueledbycaffeine/mivote/ui/voter/VoterRegistrationStatusScreen.kt
> +      modifier = Modifier.align(Alignment.CenterHorizontally)
this fails to compile in compose alpha04, update your AS

2020-10-11 04:01 UTC, joshfriend commented on app/src/main/java/com/fueledbycaffeine/mivote/ui/voter/VoterRegistrationStatusScreen.kt
> +  Box(
deprecated in alpha04, import from the new location to fix

2020-10-11 04:01 UTC, joshfriend commented on app/src/main/java/com/fueledbycaffeine/mivote/ui/Type.kt
> +import com.fueledbycaffeine.mivote.R
These fonts are available from google fonts, which means you can use the neato downloadable font resources thing to get them instead of bundling with the app: https://github.com/googlearchive/android-DownloadableFonts/blob/master/app/src/main/res/font/lobster_two.xml

2020-10-11 04:01 UTC, joshfriend commented on app/src/main/java/com/fueledbycaffeine/mivote/ui/Type.kt
> +private val hind = fontFamily(
custom typefaces seem to break compose alpha04 preview window.

```
java.lang.IllegalStateException: Cannot create Typeface from ResourceFont(resId=2131230721, weight=FontWeight(weight=700), style=Normal)
	at androidx.compose.ui.text.platform.TypefaceAdapter.create(TypefaceAdapter.kt:245)
	at androidx.compose.ui.text.platform.TypefaceAdapter.create(TypefaceAdapter.kt:145)
	at androidx.compose.ui.text.platform.extensions.TextPaintExtensionsKt.createTypeface(TextPaintExtensions.kt:152)
	at androidx.compose.ui.text.platform.extensions.TextPaintExtensionsKt.applySpanStyle(TextPaintExtensions.kt:57)
	at androidx.compose.ui.text.platform.AndroidParagraphIntrinsics.<init>(AndroidParagraphIntrinsics.kt:67)
	...
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I filed a bug for it https://issuetracker.google.com/issues/170540515

2020-10-11 18:48 UTC, scottschmitz commented on app/src/main/java/com/fueledbycaffeine/mivote/ui/voter/VoterRegistrationStatusScreen.kt
> +  Box(
Updated.

2020-10-11 19:08 UTC, scottschmitz commented on app/src/main/java/com/fueledbycaffeine/mivote/ui/Type.kt
> +private val hind = fontFamily(
![image](https://user-images.githubusercontent.com/1085240/95687739-8a3a1780-0bd3-11eb-9c25-333aff75c0b0.png)

Idk still seems to work for me

2020-10-11 23:51 UTC, joshfriend commented on app/src/main/java/com/fueledbycaffeine/mivote/ui/Type.kt
> +private val hind = fontFamily(
¯\\\_(ツ)_/¯

2020-10-12 01:10 UTC, joshfriend approved these changes

2020-10-12 01:10 UTC, merged